### ISSUE TITLE
REGISTRAR ENFERMERO-AUXILIAR

### ISSUE THREAD

**Issue by JohanSA7** [JohanSA7/PfizerAtHome#28]

**Comment by lbandoa** [comment]
<!doctype html>
<html lang="en">
    <head>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="estilos.css">

        <title>REGISTRO ENFERMERO AUXILIAR</title>
    </head>
    <body>
        <h3>REGISTRO ENFERMERO AUXILIAR</h3>
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="shadow-lg p-3 mb-5 mt-4 bg-body rounded">
                        <form class="row g-3 needs-validation" novalidate>
                            <div class="col-md-3 position-relative">
                                <label for="nombre" class="form-label">Nombres</label>
                                <input id="nombre" name="nombre" type="text" class="form-control" required>
                                
                                <div class="valid-tooltip">Campo ok</div>
                                <div class="invalid-tooltip">Complete los datos</div>
                            </div>
                            <div class="col-md-4 position-relative">
                                <label for="nombre" class="form-label">Apellidos</label>
                                <input id="Apellido" name="Apellido" type="text" class="form-control" required>
                                <div class="valid-tooltip">Campo ok</div>
                                <div class="invalid-tooltip">Complete los datos</div>
                            </div>
                            <div class="col-md-3 position-relative">
                               <label for="nombre" class="form-label">Edad</label>
                               <input id="Edad" name="Edad" type="number" class="form-control" required>
                               <div class="valid-tooltip">Campo ok</div>
                               <div class="invalid-tooltip">Complete los datos</div>
                            </div>
                            <div class="col-md-4 position-relative">
                              <label for="nombre" class="form-label">Identificacion</label>
                              <input id="Identificacion" name="Identificacion" type="number" class="form-control" required>
                              <div class="valid-tooltip">Campo ok</div>
                              <div class="invalid-tooltip">Complete los datos</div>
                            </div>  
                            <div class="col-md-4 position-relative">
                                <label for="nombre" class="form-label">Telefono del auxiliar</label>
                                <input id="Telefono" name="Telefono" type="number" class="form-control" required>
                                <div class="valid-tooltip">Campo ok</div>
                                <div class="invalid-tooltip">Complete los datos</div>
                            </div>   
                            <div class="col-md-3 position-relative">
                                <label for="pais">Dirección del laboratorio</label>
                                <select name="pais" id="pais" class="form-select" required>
                                    <option selected disabled value="">Seleccione una dirección..</option>
                                    <option value="">Cra 50 # 17-56, Medellin</option>
                                    <option value="">Cll 60 sur # 117-65, Laureles</option>
                                    <option value="">Cra 80 # 66-88, Suramericana</option>
                                    <option value="">Avenida 54 # 78-01, Bello</option>
                                </select>
                              <div class="valid-tooltip">Campo ok</div>
                              <div class="invalid-tooltip">Complete los datos</div>
                              </div>   
                              <div class="col-md-3 position-relative">
                                  <label for="pais">Laboratorio</label>
                                  <select name="pais" id="pais" class="form-select" required>
                                      <option selected disabled value="">Seleccione el laboratotio..</option>
                                      <option value="">Laboratorio 01</option>
                                      <option value="">Laboratorio 02</option>
                                      <option value="">Laboratorio 03</option>
                                      <option value="">Laboratorio 04</option>
                                      <option value="">Laboratorio 05</option>
                                  </select>
                                </div>
                                <div class="valid-tooltip">Campo ok</div>
                                <div class="invalid-tooltip">Complete los datos</div>
                            </div>
                            <button type="submit" class="btn btn-warning fw-bold">Enviar</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
            
            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function () {
                'use strict'

                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.querySelectorAll('.needs-validation')

                // Loop over them and prevent submission
                Array.prototype.slice.call(forms)
                    .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                        }else{
                            alert("DATOS VALIDADOS.")
                        }

                        form.classList.add('was-validated')
                    }, false)
                    })
                })()
                
            </script>
    </body>
</html>
